# Generated by Django 3.2 on 2021-05-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0002_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat_named',
            new_name='seat_name',
        ),
    ]
