# Generated by Django 3.2 on 2021-05-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0003_rename_seat_named_seat_seat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyOneObjectcanBeCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Depts'},
        ),
    ]
