# Generated by Django 3.2 on 2021-05-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0004_auto_20210519_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlyoneobjectcanbecreated',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
