# Generated by Django 3.2 on 2021-05-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0005_onlyoneobjectcanbecreated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfRefForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orm.selfrefforeignkey')),
            ],
        ),
    ]
