# Generated by Django 3.2 on 2021-05-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0006_selfrefforeignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfrefforeignkey',
            name='greet',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
