# Generated by Django 3.2 on 2021-05-27 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0007_selfrefforeignkey_greet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfrefforeignkey',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_orm.selfrefforeignkey'),
        ),
    ]
