# Generated by Django 3.2 on 2021-06-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0008_alter_selfrefforeignkey_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'department', 'verbose_name_plural': 'Depts'},
        ),
    ]
