# Generated by Django 3.2 on 2021-05-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4_orm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_name',
            new_name='name',
        ),
    ]
